---
- name: Instalar Zsh e Git (caso não estejam instalados)
  apt:
    name:
      - zsh
      - git
    state: present

- name: Remover diretório $ZSH se existir
  file:
    path: "{{ ansible_user_dir }}/.oh-my-zsh"
    state: absent


- name: Remover ~/.zshrc se existir
  file:
    path: "{{ ansible_user_dir }}/.zshrc"
    state: absent


- name: Baixar o script de instalação do Oh My Zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"'

- name: Definir Zsh como shell padrão
  command: "chsh -s /bin/zsh {{ ansible_user }}"

- name: Adicionar configurações do Oh My Zsh ao ~/.zshrc
  blockinfile:
    path: "{{ ansible_user_dir }}/.zshrc"
    block: |
      export ZSH="{{ ansible_user_dir }}/.oh-my-zsh"
      source "$ZSH/oh-my-zsh.sh"

- name: Clonar o repositório do Spaceship Prompt
  git:
    repo: https://github.com/denysdovhan/spaceship-prompt.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt"

- name: Criar link simbólico para o tema do Spaceship Prompt
  command: ln -s "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship-prompt/spaceship.zsh-theme" "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/spaceship.zsh-theme"

- name: Clonar o repositório do zsh-syntax-highlighting
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

- name: Clonar o repositório do zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
