---
- name: Instalar Zsh e Git (caso não estejam instalados)
  apt:
    name:
      - zsh
      - git
    state: present

- name: Baixar o script de instalação do Oh My Zsh
  shell: 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
'

- name: Definir Zsh como shell padrão
  command: "chsh -s /bin/zsh {{ ansible_user }}"